coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "spec/**/*"
  - "config/**/*"
  - "db/**/*"
  - "vendor/**/*"
  - "app/channels/**/*"
