name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0' # Changed from 3.0 to 3.2.0
          bundler-cache: true # This automatically runs bundle install

      - name: Run tests
        run: |
          bundle exec rspec

      - name: Report test results
        if: always()
        run: |
          echo "Test results:"
          bundle exec rspec --format documentation
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}