name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Specify your Ruby version here

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          bundle exec rspec

      - name: Report test results
        if: always()
        run: |
          echo "Test results:"
          bundle exec rspec --format documentation
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}